### ISSUE TITLE
Review/cleanup

### ISSUE THREAD

**Issue by ruslo** [elucideye/drishti#13]
- [x] Travis/AppVeyor build
- [x] Qt binaries from server (we can use *-p7 version?)
- [ ] bin/build-all.sh on Linux
- [ ] bin/build-all.sh on OSX
- [x] tests from src/tests/drishti, CTest
- [ ] data/images: use Hunter? (see also https://github.com/elucideye/drishti/issues/19)
- [x] src/3rdparty to Hunter
- [x] local vs Hunter 3rdparty: use alias target for convenience
- [x] "namespacing" for modules
- [x] "namespacing" for options
- [ ] RPATH update, I think logic is redundant (describe [here](http://cgold.readthedocs.io/en/latest/tutorials/install/rpath.html) + fix)
- [ ] options: https://github.com/elucideye/drishti/pull/16/files/057ac42ad12a04c2e3d5fcd192d90d37a8c4ccf5..3bcbb22a5cd9405e9d40955665a4a38d15009025#r74771788

Other stuff from chat:
- [ ] ~~size of the SDK~~ (see https://github.com/elucideye/drishti/issues/5)
  - [ ] ~~O2 instead of O3?~~
  - [ ] ~~MinSizeRel?~~
  - [ ] ~~Link Time Optimization?~~
  - [ ] ~~Single Compilation Unit?~~
- [ ] build time (Hunter binary cache enough? ~~Try Travis directory cache~~ (see [comment](https://github.com/elucideye/drishti/issues/13#issuecomment-243860301))
