### ISSUE TITLE
Build with Qt

### ISSUE THREAD

**Issue by ruslo** [elucideye/drishti#189]
- [x] Android: ~~https://github.com/elucideye/drishti/issues/186~~ https://github.com/elucideye/drishti/issues/221
- [x] [iOS 10.1](https://github.com/elucideye/drishti/issues/184)
- [x] iOS 9.3 (`ios-9-3-armv7` tested on iPhone 4S)
- [x] OSX (`osx-10-11` [works fine](https://github.com/elucideye/drishti/pull/190))
- [ ] [Windows](https://github.com/elucideye/drishti/issues/179)
- [ ] [Linux](https://github.com/elucideye/drishti/issues/178)

**Comment by ruslo** [comment]
https://github.com/elucideye/drishti/issues/511#issuecomment-323573932

Closing
