### ISSUE TITLE
TODO: hunter-packages

### ISSUE THREAD

**Issue by headupinclouds** [elucideye/drishti#358]
- [x] https://github.com/hunter-packages/sse2neon (acf)
- [x] https://github.com/hunter-packages/ARM_NEON_2_x86_SSE (core)
- [ ] https://github.com/hunter-packages/ogles_gpgpu
- [x] imshow : add texture access to api + support nonContinuous
- [x] glfw : update to 3.3 to prevent Mac OS Sierra warning (occasional crash) https://github.com/glfw/glfw/issues/876#issuecomment-254043008

```
2017-03-31 23:14:53.278493 test-ogles_gpgpu[66374:19119633] [General] ERROR: Setting <GLFWContentView: 0x100c2dd10> as the first responder for window <GLFWWindow: 0x100b0b3a0>, but it is in a different window ((null))! This would eventually crash when the view is freed. The first responder will be set to nil.
(
	0   AppKit                              0x00007fffba1f8114 -[NSWindow _validateFirstResponder:] + 566
	1   AppKit                              0x00007fffb99747ff -[NSWindow _setFirstResponder:] + 31
	2   AppKit                              0x00007fffb9a1ca22 -[NSWindow _realMakeFirstResponder:] + 406
	3   AppKit                              0x00007fffb9a1c838 -[NSWindow makeFirstResponder:] + 123
	4   test-ogles_gpgpu                    0x0000000100106dee createWindow + 1230
```
